studio-330418259:~/studio{master}$ firebase deploy
=== Deploying to 'ai-resume-be9c1'...

i  deploying storage, firestore, functions, hosting
i  storage: ensuring required API firebasestorage.googleapis.com is enabled...
✔  storage: required API firebasestorage.googleapis.com is enabled
i  firebase.storage: checking storage.rules for compilation errors...
✔  firebase.storage: rules file storage.rules compiled successfully
i  firestore: reading indexes from firestore.indexes.json...
i  cloud.firestore: checking firestore.rules for compilation errors...
✔  cloud.firestore: rules file firestore.rules compiled successfully
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
i  functions: Loading and analyzing source code for codebase default to determine what to deploy
Serving at port 8561

i  extensions: ensuring required API firebaseextensions.googleapis.com is enabled...
✔  extensions: required API firebaseextensions.googleapis.com is enabled
i  storage: uploading rules storage.rules...
i  firestore: deploying indexes...
✔  firestore: deployed indexes in firestore.indexes.json successfully for (default) database
i  firestore: latest version of firestore.rules already up to date, skipping upload...
i  hosting[ai-resume-be9c1]: beginning deploy...

Error: Directory 'out' for Hosting does not exist.

Having trouble? Try firebase [command] --help
studio-330418259:~/studio{master}$