studio-330418259:~/studio{master}$ npm run build
> magicsaver-rebuild@0.1.0 build
> next build

  ▲ Next.js 14.2.5
  - Environments: .env.local

   Creating an optimized production build ...
 ✓ Compiled successfully
   Linting and checking validity of types  ..Failed to compile.

./src/app/admin/clicks/page.tsx:413:83
Type error: Property 'toDate' does not exist on type 'Timestamp | FieldValue'.
  Property 'toDate' does not exist on type 'FieldValue'.

  411 |                             </TableCell>
  412 |                             <TableCell className="whitespace-nowrap">
> 413 |                               {clickTimestampObject ? format(clickTimestampObject.toDate(), 'PPp') : 'N/A'}
      |                                                                                   ^
  414 |                             </TableCell>
  415 |                             <TableCell>
  416 |                               {conversion ? (
studio-330418259:~/studio{master}$