FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/ai-resume-be9c1/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9haS1yZXN1bWUtYmU5YzEvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL2NvdXBvbnMvaW5kZXhlcy9fEAEaDAoIaXNBY3RpdmUQARoNCgljcmVhdGVkQXQQAhoMCghfX25hbWVfXxAC