studio-330418259:~/studio{master}$ firebase deploy --only firestore:indexes
=== Deploying to 'ai-resume-be9c1'...

i  deploying firestore
i  firestore: reading indexes from firestore.indexes.json...
i  cloud.firestore: checking firestore.rules for compilation errors...
✔  cloud.firestore: rules file firestore.rules compiled successfully
i  firestore: deploying indexes...
i  firestore: The following indexes are defined in your project but are not present in your firestore indexes file:
        (stores) -- (categories,CONTAINS) (isActive,ASCENDING) (name,ASCENDING)
        (payoutRequests) -- (status,ASCENDING) (requestedAt,ASCENDING)
        (stores) -- (isActive,ASCENDING) (name,ASCENDING)
        (stores) -- (isActive,ASCENDING) (isFeatured,DESCENDING) (name,ASCENDING)
        (coupons) -- (storeId,ASCENDING) (isActive,ASCENDING) (isFeatured,DESCENDING) (createdAt,DESCENDING)
        (coupons) -- (isActive,ASCENDING) (isFeatured,DESCENDING) (createdAt,DESCENDING)
        (coupons) -- (storeId,ASCENDING) (isActive,ASCENDING) (createdAt,DESCENDING)
        (transactions) -- (userId,ASCENDING) (status,ASCENDING)
? Would you like to delete these indexes? Selecting no will continue the rest of the deployment. No

Error: Request to https://firestore.googleapis.com/v1/projects/ai-resume-be9c1/databases/(default)/collectionGroups/users/indexes had HTTP Error: 400, this index is not necessary, configure using single field index controls
studio-330418259:~/studio{master}$